IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'rip')
EXEC sys.sp_executesql N'CREATE SCHEMA [rip]'
GO
IF  NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'ripWsRep')
EXEC sys.sp_executesql N'CREATE SCHEMA [ripWsRep]'
GO
/****** Object:  Table [rip].[CONTEOCAB]    Script Date: 23/8/2023 8:58:45 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[CONTEOCAB]') AND type in (N'U'))
BEGIN
CREATE TABLE [rip].[CONTEOCAB](
	[FECHA] [date] NOT NULL,
	[CODALMACEN] [nvarchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[OBSERVACION] [nvarchar](50) COLLATE Modern_Spanish_CI_AS NULL,
	[FECHAINICIO] [datetime] NULL,
	[FECHAFIN] [datetime] NULL,
	[IDCONTEO] [int] NULL,
 CONSTRAINT [PK_CONTEOCAB] PRIMARY KEY CLUSTERED 
(
	[FECHA] ASC,
	[CODALMACEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [rip].[CONTEOLIN]    Script Date: 23/8/2023 8:58:45 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[CONTEOLIN]') AND type in (N'U'))
BEGIN
CREATE TABLE [rip].[CONTEOLIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [date] NOT NULL,
	[CODALMACEN] [nvarchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[CODARTICULO] [int] NOT NULL,
	[COLOR] [nvarchar](10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[TALLA] [nvarchar](10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[UNIDADES] [float] NOT NULL,
	[HORACONTEO] [datetime] NOT NULL,
 CONSTRAINT [PK_CONTEOLIN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[CONCEPTOS_CONTEO]') AND type in (N'U'))
BEGIN
CREATE TABLE [rip].[CONCEPTOS_CONTEO](
	[CODCONCEPTO] [int] NOT NULL,
	[CONCEPTO] [nvarchar](30) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_rip.CONCEPTOS_CONTEO] PRIMARY KEY CLUSTERED 
(
	[CODCONCEPTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END

GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[rip].[FK_CONTEOLIN_CONTEOCAB]') AND parent_object_id = OBJECT_ID(N'[rip].[CONTEOLIN]'))
ALTER TABLE [rip].[CONTEOLIN]  WITH CHECK ADD  CONSTRAINT [FK_CONTEOLIN_CONTEOCAB] FOREIGN KEY([FECHA], [CODALMACEN])
REFERENCES [rip].[CONTEOCAB] ([FECHA], [CODALMACEN])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[rip].[FK_CONTEOLIN_CONTEOCAB]') AND parent_object_id = OBJECT_ID(N'[rip].[CONTEOLIN]'))
ALTER TABLE [rip].[CONTEOLIN] CHECK CONSTRAINT [FK_CONTEOLIN_CONTEOCAB]
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'IDTIPOCONTEO' AND object_id = OBJECT_ID('rip.CONTEOCAB'))
BEGIN
ALTER TABLE [rip].[CONTEOCAB]
ADD [IDTIPOCONTEO] [int] DEFAULT 1
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'ZONA' AND object_id = OBJECT_ID('rip.CONTEOLIN'))
BEGIN
ALTER TABLE [rip].[CONTEOLIN]
ADD [ZONA] nvarchar(50) NULL
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'CODUSUARIO' AND object_id = OBJECT_ID('rip.CONTEOLIN'))
BEGIN
ALTER TABLE [rip].[CONTEOLIN]
ADD [CODUSUARIO] [int] NULL
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'CODCONCEPTO' AND object_id = OBJECT_ID('rip.CONTEOLIN'))
BEGIN
ALTER TABLE [rip].[CONTEOLIN]
ADD [CODCONCEPTO] [int] DEFAULT 1
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'SECTOR' AND object_id = OBJECT_ID('rip.CONTEOLIN'))
BEGIN
ALTER TABLE [rip].[CONTEOLIN]
ADD [SECTOR] [int] DEFAULT 1
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'UNIDADESREALES' AND object_id = OBJECT_ID('rip.CONTEOLIN'))
BEGIN
ALTER TABLE [rip].[CONTEOLIN]
ADD [UNIDADESREALES] [float] NULL
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'IDENVIO' AND object_id = OBJECT_ID('rip.CONTEOLIN'))
BEGIN
ALTER TABLE [rip].[CONTEOLIN]
ADD [IDENVIO] [uniqueidentifier] NULL
END

GO
IF NOT EXISTS (SELECT 1 
               FROM sys.indexes 
               WHERE name = 'IX_CONTEOCAB' 
               AND object_id = OBJECT_ID('rip.CONTEOCAB'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [IX_CONTEOCAB] ON [rip].[CONTEOCAB]
    (
        [IDCONTEO] ASC
    ) 
    WITH (
        PAD_INDEX = OFF, 
        STATISTICS_NORECOMPUTE = OFF, 
        SORT_IN_TEMPDB = OFF, 
        IGNORE_DUP_KEY = OFF, 
        DROP_EXISTING = OFF, 
        ONLINE = OFF, 
        ALLOW_ROW_LOCKS = ON, 
        ALLOW_PAGE_LOCKS = ON
    ) 
    ON [PRIMARY];
END
GO
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_CONTEOLIN' 
      AND object_id = OBJECT_ID('[rip].[CONTEOLIN]')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_CONTEOLIN] ON [rip].[CONTEOLIN]
    (
        [FECHA] ASC,
        [CODALMACEN] ASC
    )
    WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        SORT_IN_TEMPDB = OFF,
        DROP_EXISTING = OFF,
        ONLINE = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY];
END;

GO
/****** Object:  Table [rip].[CONTEOSTOCK]    Script Date: 11/9/2023 4:48:10 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[CONTEOSTOCK]') AND type in (N'U'))
BEGIN
CREATE TABLE [rip].[CONTEOSTOCK](
	[CODALMACEN] [nvarchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[FECHA] [date] NOT NULL,
	[CODARTICULO] [int] NOT NULL,
	[COLOR] [nvarchar](10) COLLATE Latin1_General_CS_AI NOT NULL,
	[TALLA] [nvarchar](10) COLLATE Latin1_General_CS_AI NOT NULL,
	[STOCK] [float] NULL,
 CONSTRAINT [PK_CONTEOSTOCK] PRIMARY KEY CLUSTERED 
(
	[CODALMACEN] ASC,
	[FECHA] ASC,
	[CODARTICULO] ASC,
	[COLOR] ASC,
	[TALLA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

DELETE FROM [rip].[CONCEPTOS_CONTEO]
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (1, N'PISO DE VENTA')
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (2, N'BODEGA INTERNA')
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (3, N'BODEGA EXTERNA')
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (4, N'TESTER')
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (5, N'DEFECTUOSO')
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (6, N'DOTACION')
GO
INSERT [rip].[CONCEPTOS_CONTEO] ([CODCONCEPTO], [CONCEPTO]) VALUES (7, N'OTRAS ZONAS')

GO
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[CONTEO_ENVIOS]') AND type in (N'U'))
BEGIN
CREATE TABLE [rip].[CONTEO_ENVIOS](
	[ID] [uniqueidentifier] NOT NULL DEFAULT (newid()),
	[IP] [varchar](16) COLLATE Modern_Spanish_CI_AS NULL,
	[PROCESADO] [bit]  DEFAULT ((0)),
	[HORAGENERADO] [datetime] DEFAULT (getdate()),
	[HORAPROCESADO] [datetime] NULL,
 CONSTRAINT [PK_CONTEO_ENVIOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'CODUSUARIO' AND object_id = OBJECT_ID('rip.CONTEO_ENVIOS'))
BEGIN
ALTER TABLE [rip].[CONTEO_ENVIOS]
ADD [CODUSUARIO] [int] NULL
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'UNIDADES' AND object_id = OBJECT_ID('rip.CONTEO_ENVIOS'))
BEGIN
ALTER TABLE [rip].[CONTEO_ENVIOS]
ADD [UNIDADES] [float] NULL
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'IDCONTEO' AND object_id = OBJECT_ID('rip.CONTEO_ENVIOS'))
BEGIN
ALTER TABLE [rip].[CONTEO_ENVIOS]
ADD [IDCONTEO] [int] NULL
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'PREPROCESADO' AND object_id = OBJECT_ID('rip.CONTEO_ENVIOS'))
BEGIN
ALTER TABLE rip.CONTEO_ENVIOS 
ADD  [PREPROCESADO] [bit] DEFAULT 0
END
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE name = 'SCRIPTSQL' AND object_id = OBJECT_ID('rip.CONTEO_ENVIOS'))
BEGIN
ALTER TABLE rip.CONTEO_ENVIOS 
ADD  [SCRIPTSQL] VARCHAR(MAX) DEFAULT NULL
END
GO
/****** Object:  Table [rip].[CONTEO_TARGET]    Script Date: 16/9/2024 7:50:23 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[CONTEO_TARGET]') AND type in (N'U'))
BEGIN
CREATE TABLE [rip].[CONTEO_TARGET](
	[IDCONTEO] [int] NOT NULL,
	[CODARTICULO] [int] NOT NULL,
	[ASIGNADO] [bit] NULL,
	[BLOQUE] [int] NOT NULL,
	[IDBLOQUE] [nvarchar](40) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_CONTEO_TARGET] PRIMARY KEY CLUSTERED 
(
	[IDCONTEO] ASC,
	[CODARTICULO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[DF_CONTEO_TARGET_BLOQUE]') AND type = 'D')
BEGIN
ALTER TABLE [rip].[CONTEO_TARGET] ADD  CONSTRAINT [DF_CONTEO_TARGET_BLOQUE]  DEFAULT ((0)) FOR [BLOQUE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[rip].[FK_CONTEO_TARGET_CONTEO_TARGET]') AND parent_object_id = OBJECT_ID(N'[rip].[CONTEO_TARGET]'))
ALTER TABLE [rip].[CONTEO_TARGET]  WITH CHECK ADD  CONSTRAINT [FK_CONTEO_TARGET_CONTEO_TARGET] FOREIGN KEY([IDCONTEO], [CODARTICULO])
REFERENCES [rip].[CONTEO_TARGET] ([IDCONTEO], [CODARTICULO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[rip].[FK_CONTEO_TARGET_CONTEO_TARGET]') AND parent_object_id = OBJECT_ID(N'[rip].[CONTEO_TARGET]'))
ALTER TABLE [rip].[CONTEO_TARGET] CHECK CONSTRAINT [FK_CONTEO_TARGET_CONTEO_TARGET]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[rip].[FK_CONTEO_TARGET_CONTEOCAB]') AND parent_object_id = OBJECT_ID(N'[rip].[CONTEO_TARGET]'))
ALTER TABLE [rip].[CONTEO_TARGET]  WITH CHECK ADD  CONSTRAINT [FK_CONTEO_TARGET_CONTEOCAB] FOREIGN KEY([IDCONTEO])
REFERENCES [rip].[CONTEOCAB] ([IDCONTEO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[rip].[FK_CONTEO_TARGET_CONTEOCAB]') AND parent_object_id = OBJECT_ID(N'[rip].[CONTEO_TARGET]'))
ALTER TABLE [rip].[CONTEO_TARGET] CHECK CONSTRAINT [FK_CONTEO_TARGET_CONTEOCAB]
GO

-- A PARTIR DE AQUI SON TODOS LOS PROCEDIMIENTOS Y FUNCIONES
GO
/****** Object:  StoredProcedure [ripWsRep].[GET_VENDEDORES]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripWsRep].[GET_VENDEDORES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [ripWsRep].[GET_VENDEDORES]
GO
/****** Object:  StoredProcedure [ripWsRep].[GET_ALMACENES]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripWsRep].[GET_ALMACENES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [ripWsRep].[GET_ALMACENES]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_GETCONTEO_ARTICULO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_GETCONTEO_ARTICULO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_GETCONTEO_ARTICULO]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_GETCONTEO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_GETCONTEO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_GETCONTEO]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_DETALLE_ARTICULO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_DETALLE_ARTICULO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_DETALLE_ARTICULO]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_DETALLE]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_DETALLE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_DETALLE]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_DETALLE_PTY]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_DETALLE_PTY]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_DETALLE_PTY]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_BUSCAR_ARTICULOS]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_BUSCAR_ARTICULOS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_BUSCAR_ARTICULOS]
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_BUSCAR_ARTICULO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[APP_CONTEO_BUSCAR_ARTICULO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [rip].[APP_CONTEO_BUSCAR_ARTICULO]
GO
/****** Object:  UserDefinedFunction [rip].[RIP_FSTOCK_ARTICULO_FECHA]    Script Date: 11/9/2023 9:25:17 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[rip].[RIP_FSTOCK_ARTICULO_FECHA]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [rip].[RIP_FSTOCK_ARTICULO_FECHA]
GO
/****** Object:  UserDefinedFunction [rip].[RIP_FSTOCK_ARTICULO_FECHA]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE FUNCTION [rip].[RIP_FSTOCK_ARTICULO_FECHA] (@FECHA AS DATETIME, @ALMACEN AS NVARCHAR(4) )
RETURNS TABLE
WITH ENCRYPTION AS RETURN (
SELECT  A.CODARTICULO, A.COLOR, A.TALLA,
 ROUND(SUM(ISNULL(REG,0))+SUM(ISNULL(REC,0))+SUM(ISNULL(COMP,0))-SUM(ISNULL(ENV,0))-SUM(ISNULL(VEN,0))-SUM(ISNULL(CON,0))-SUM(ISNULL(FAB_SAL,0))+SUM(ISNULL(FAB_ENT,0)),3) AS STOCK,
 SUM(ISNULL(REG,0)) REG,SUM(ISNULL(REC,0)) REC,SUM(ISNULL(COMP,0)) COMP,SUM(ISNULL(ENV,0)) ENV, SUM(ISNULL(VEN,0)) VEN,SUM(ISNULL(CON,0)) CON, SUM(ISNULL(FAB_ENT,0)) FAB_ENT
 , SUM(ISNULL(FAB_SAL,0)) FAB_SAL
 FROM (
SELECT CODALMACENORIGEN AS CODALMACEN, A.CODARTICULO, A.COLOR, A.TALLA,0 AS FECHA, 0.0 AS REG,
0.0 AS REC, 0.0 AS COMP, 0.0 AS ENV, 0.0 AS VEN, SUM(UNIDADES) AS CON, 0.0 FAB_SAL, 0.0 FAB_ENT
FROM (SELECT A.* FROM MOVIMENTS AS A INNER JOIN CONSUMOSCAB AS B
ON A.SERIEDOC=B.SERIE AND A.NUMDOC=B.NUMERO AND A.TIPO='CON'  WHERE B.FECHA <= @FECHA ) AS A
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS B ON A.CODALMACENORIGEN=B.CODALMACEN AND A.CODARTICULO=B.CODARTICULO AND A.TALLA=B.TALLA AND A.COLOR=B.COLOR
WHERE A.FECHA>=B.FECHA OR B.FECHA IS NULL 
GROUP BY CODALMACENORIGEN, A.CODARTICULO, A.COLOR, A.TALLA
UNION ALL
SELECT CODALMACENORIGEN AS CODALMACEN, A.CODARTICULO, A.COLOR, A.TALLA,0 AS FECHA, 0 AS REG,
0 AS REC, 0 AS COMP, SUM(UNIDADES) AS ENV, 0 AS VEN, 0 AS CON, 0 FAB_SAL, 0 FAB_ENT
FROM (SELECT A.* FROM MOVIMENTS AS A INNER JOIN TRASPASOSCAB AS B
ON A.SERIEDOC=B.SERIE AND A.NUMDOC=B.NUMERO AND A.CAJA=B.CAJA WHERE A.TIPO='ENV' AND B.FECHA <= @FECHA ) AS A
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS B ON A.CODALMACENORIGEN=B.CODALMACEN AND A.CODARTICULO=B.CODARTICULO AND A.TALLA=B.TALLA AND A.COLOR=B.COLOR
WHERE A.FECHA>=B.FECHA OR B.FECHA IS NULL
GROUP BY CODALMACENORIGEN, A.CODARTICULO, A.COLOR, A.TALLA

UNION ALL
SELECT CODALMACENDESTINO AS CODALMACEN, A.CODARTICULO, A.COLOR, A.TALLA, MAX(A.FECHA) AS FECHA,  0 AS REG,
SUM(UNIDADES) AS REC, 0 AS COMP, 0  AS ENV, 0 AS VEN, 0 AS CON, 0 FAB_SAL, 0 FAB_ENT
FROM (SELECT A.*, B.FECHARECIBIDO FROM MOVIMENTS AS A INNER JOIN TRASPASOSCAB AS B
ON A.SERIEDOC=B.SERIE AND A.NUMDOC=B.NUMERO AND A.CAJA=B.CAJA WHERE A.TIPO='ENV' AND B.FECHARECIBIDO <= @FECHA AND B.RECIBIDO='T' ) AS A
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS C ON A.CODALMACENDESTINO=C.CODALMACEN AND A.CODARTICULO=C.CODARTICULO AND A.TALLA=C.TALLA AND A.COLOR=C.COLOR
WHERE A.FECHARECIBIDO>=C.FECHA OR C.FECHA IS NULL AND UNIDADES<>0
GROUP BY CODALMACENDESTINO, A.CODARTICULO,A.COLOR, A.TALLA
UNION ALL
SELECT A.* FROM (
SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, FECHA, SUM(UNIDADES) AS REG,
0 AS REC, 0 AS COMP, 0  AS ENV, 0 AS VEN, 0 AS CON, 0 FAB_SAL, 0 FAB_ENT
FROM MOVIMENTS  WHERE   TIPO='REG'  AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA, FECHA) AS A INNER JOIN
(SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE   TIPO='REG' AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA) AS B
ON A.CODALMACEN=B.CODALMACEN AND A.CODARTICULO=B.CODARTICULO AND A.COLOR=B.COLOR AND A.TALLA=B.TALLA
AND A.FECHA=B.FECHA
UNION ALL
SELECT B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA, 0 AS FECHA, 0 AS REG,0 AS REC,
SUM(COMP) AS COMP, 0 AS ENV, 0 AS VEN, 0 AS CON, 0 FAB_SAL, 0 FAB_ENT FROM
(SELECT B.CODALMACEN, B.CODARTICULO, B.COLOR, B.TALLA,  FECHAALBARAN AS FECHA,  SUM(UNIDADESTOTAL) AS COMP
FROM ALBCOMPRACAB AS A INNER JOIN ALBCOMPRALIN AS B ON A.NUMSERIE=B.NUMSERIE AND A.NUMALBARAN=B.NUMALBARAN
WHERE  FECHAALBARAN <= @FECHA
GROUP BY B.CODALMACEN, B.CODARTICULO, B.COLOR, B.TALLA, UNIDADESTOTAL, FECHAALBARAN ) AS B
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS C ON B.CODALMACEN=C.CODALMACEN AND B.CODARTICULO=C.CODARTICULO AND B.TALLA=C.TALLA AND B.COLOR=C.COLOR
WHERE (B.FECHA>=C.FECHA OR C.FECHA IS NULL)
GROUP BY B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA
UNION ALL
--VENTAS DE KITS
SELECT B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA, 0 AS FECHA, 0 AS REG,0 AS REC,
0 AS COMP, 0 AS ENV, SUM(VEN)  AS VEN, 0 AS CON, 0 FAB_SAL, 0 FAB_ENT FROM
(SELECT B.CODALMACEN,  B.CODARTICULO CODARTICULO,B.TALLA TALLA
,  B.COLOR COLOR,
FECHA, SUM(UNIDADESTOTAL) AS VEN
FROM ALBVENTACAB AS A INNER JOIN ALBVENTALIN AS B ON A.NUMSERIE=B.NUMSERIE AND A.NUMALBARAN=B.NUMALBARAN
INNER JOIN ARTICULOS ART ON B.CODARTICULO=ART.CODARTICULO AND ART.USASTOCKS='T'
INNER JOIN TIPOSDOC TD ON A.TIPODOC=TD.TIPODOC 
WHERE  FECHA <= @FECHA
	AND TD.STOCK='T'
GROUP BY B.CODALMACEN, B.CODARTICULO, B.COLOR, B.TALLA, UNIDADESTOTAL, FECHA ) AS B
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS C ON B.CODALMACEN=C.CODALMACEN AND B.CODARTICULO=C.CODARTICULO AND B.TALLA=C.TALLA AND B.COLOR=C.COLOR
WHERE (B.FECHA>=C.FECHA OR C.FECHA IS NULL) 
GROUP BY B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA
--VENTAS DE ARTICULOS QUE SON KITS Y NO MANEJAN STOCK


--ESTA DE ABAJO ES LA CONSULTA VIEJTA
/*SELECT B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA, 0 AS FECHA, 0 AS REG,0 AS REC,
0 AS COMP, 0 AS ENV, SUM(VEN)  AS VEN, 0 AS CON, 0 FAB_SAL, 0 FAB_ENT FROM
(SELECT B.CODALMACEN,  ISNULL(K.CODARTKIT,B.CODARTICULO) CODARTICULO,ISNULL(K.TALLAKIT,B.TALLA) TALLA,  ISNULL(K.COLORKIT,B.COLOR) COLOR,
FECHA, SUM(UNIDADESTOTAL*ISNULL(K.UNIDADES,1)) AS VEN
FROM ALBVENTACAB AS A INNER JOIN ALBVENTALIN AS B ON A.NUMSERIE=B.NUMSERIE AND A.NUMALBARAN=B.NUMALBARAN
LEFT JOIN KITS K ON K.CODARTICULO=B.CODARTICULO AND K.COLOR=B.COLOR AND K.TALLA=B.TALLA
WHERE  FECHA <= @FECHA
GROUP BY B.CODALMACEN, B.CODARTICULO, B.COLOR, B.TALLA, UNIDADESTOTAL, FECHA , K.CODARTKIT, K.COLORKIT, K.TALLAKIT ) AS B
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS C ON B.CODALMACEN=C.CODALMACEN AND B.CODARTICULO=C.CODARTICULO AND B.TALLA=C.TALLA AND B.COLOR=C.COLOR
WHERE (B.FECHA>=C.FECHA OR C.FECHA IS NULL)
GROUP BY B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA*/
--FABRICACIONES SALIENTES
UNION ALL
SELECT B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA, 0 AS FECHA, 0 AS REG,0 AS REC,
0 AS COMP, 0 AS ENV, 0 AS VEN, 0 AS CON, SUM(B.UNIDADES) AS FAB_SAL, 0 AS FAB_ENT FROM
(SELECT FAB.ALMACENORIGEN CODALMACEN, FAB.CODIGOART CODARTICULO, FAB.COLOR, FAB.TALLA, FAB.FECHAFIN FECHA, SUM(UDSTOTAL) UNIDADES
FROM(
SELECT
	DISTINCT OFL.CODIGOART, OFL.COLOR, OFL.TALLA, OFL.UDSTOTAL, OFC.FECHAFIN, OFC.ALMACENORIGEN, OFC.SERIE, OFC.NUMERO
FROM
	ORDENESFABCAB OFC INNER JOIN ORDENESFABLIN OFL ON OFC.SERIE=OFL.SERIE AND OFC.NUMERO=OFL.NUMERO
WHERE
	OFC.ACABADA='T' AND OFC.FECHAFIN<@FECHA) FAB
GROUP BY FAB.ALMACENORIGEN, FAB.CODIGOART, FAB.COLOR, FAB.TALLA, FAB.FECHAFIN) B
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS C ON B.CODALMACEN=C.CODALMACEN AND B.CODARTICULO=C.CODARTICULO AND B.TALLA=C.TALLA AND B.COLOR=C.COLOR
WHERE (B.FECHA>=C.FECHA OR C.FECHA IS NULL)
GROUP BY B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA

--FABRICACIONES ENTRANTES
UNION ALL
SELECT  B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA, 0 AS FECHA, 0 AS REG,0 AS REC,
0 AS COMP, 0 AS ENV, 0 AS VEN, 0 AS CON, 0 FAB_SAL, SUM(UNIDADES) FAB_ENT  FROM (
SELECT
	DISTINCT OFC.ALMACENDESTINO CODALMACEN, OFC.CODIGOART CODARTICULO, OFC.COLOR, OFC.TALLA, OFC.FECHAFIN FECHA, SUM(OFC.UNIDADES)UNIDADES
FROM
	ORDENESFABCAB OFC 
WHERE
	OFC.ACABADA='T' AND OFC.FECHAFIN<@FECHA
GROUP BY OFC.ALMACENDESTINO, OFC.CODIGOART, OFC.COLOR, OFC.TALLA, OFC.FECHAFIN) B
LEFT JOIN ( SELECT CODALMACENORIGEN AS CODALMACEN, CODARTICULO, COLOR, TALLA, MAX(FECHA) AS FECHA
FROM MOVIMENTS  WHERE  TIPO='REG' AND  FECHA <= @FECHA
GROUP BY CODALMACENORIGEN, CODARTICULO, COLOR, TALLA
)AS C ON B.CODALMACEN=C.CODALMACEN AND B.CODARTICULO=C.CODARTICULO AND B.TALLA=C.TALLA AND B.COLOR=C.COLOR
WHERE (B.FECHA>=C.FECHA OR C.FECHA IS NULL)
GROUP BY B.CODALMACEN, B.CODARTICULO,B.COLOR, B.TALLA

) AS A
INNER JOIN ARTICULOS ART ON A.CODARTICULO=ART.CODARTICULO AND ART.TIPOARTICULO='A' AND ART.USASTOCKS='T'
INNER JOIN ARTICULOSLIN AL ON ART.CODARTICULO=AL.CODARTICULO AND A.COLOR=AL.COLOR AND A.TALLA=AL.TALLA 
WHERE A.CODALMACEN=@ALMACEN
GROUP BY  A.CODARTICULO, A.COLOR, A.TALLA
)
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_BUSCAR_ARTICULO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [rip].[APP_CONTEO_BUSCAR_ARTICULO](@CODIGO AS NVARCHAR(50)
					, @CODALMACEN AS NVARCHAR(3) 
					, @CODARTICULO AS INT=-1
					, @COLOR AS NVARCHAR(10)=''
					, @TALLA AS NVARCHAR(10)='')
WITH ENCRYPTION AS SET NOCOUNT ON
BEGIN
;WITH CTE_ARTICULOS  AS (
		SELECT 
				distinct
				A.CODARTICULO
				, A.REFPROVEEDOR
				, A.DESCRIPCION
				, AL.COLOR
				, AL.TALLA
				, AL.CODBARRAS
				--, ISNULL(TRY_CONVERT(DATE,AL.CODBARRAS2,3),'20000101') CODBARRAS2
                                , '20000101' CODBARRAS2
				, AL.CODBARRAS3
				, A.USASTOCKS
				, A.MARCA
				, A.ESKIT
				, A.USARNUMSERIE
				, A.UNID2V
				, ISNULL(SEC.DESCRIPCION,'SIN SECCION') SECCION
		FROM 
				ARTICULOS A WITH(NOLOCK)
				INNER JOIN ARTICULOSLIN AL WITH(NOLOCK) ON A.CODARTICULO=AL.CODARTICULO
				INNER JOIN REFERENCIASPROV RP WITH(NOLOCK) ON A.CODARTICULO=RP.CODARTICULO
				LEFT JOIN SECCIONES SEC WITH(NOLOCK) ON A.DPTO=SEC.NUMDPTO AND A.SECCION=SEC.NUMSECCION
		WHERE A.TIPOARTICULO='A'
				AND A.DESCATALOGADO='F'
				AND ( (UPPER(AL.CODBARRAS)=@CODIGO OR UPPER(A.REFPROVEEDOR)=@CODIGO OR UPPER(AL.CODBARRAS2)=@CODIGO OR UPPER(AL.CODBARRAS3)=@CODIGO OR UPPER(RP.REFPROVEEDOR)=@CODIGO
                                        OR UPPER(A.NORMA) LIKE '%'+@CODIGO+'%' --OJO ESTO ES POR ALGO DE WYNWOOD 
                                    ) 
					OR
					(AL.CODARTICULO=@CODARTICULO AND AL.COLOR=@COLOR AND AL.TALLA=@TALLA ) ) 

),CTE_STOCK AS (
		SELECT 
				CODALMACEN, CODARTICULO,COLOR, TALLA, SUM(STOCK) STOCK
		FROM 
				STOCKS S WITH(NOLOCK)
		WHERE
				S.CODALMACEN=@CODALMACEN
		GROUP BY 
				CODALMACEN, CODARTICULO,COLOR, TALLA
), CTE_ARTICULOS_STOCK AS (
		SELECT 
				A.*, ISNULL(S.STOCK,0) STOCK
		 FROM 
				CTE_ARTICULOS A
				LEFT JOIN CTE_STOCK S ON A.CODARTICULO=S.CODARTICULO AND A.COLOR=S.COLOR AND A.TALLA=S.TALLA

)
--SELECT * FROM CTE_STOCK

SELECT
	A.CODARTICULO
	, A.REFPROVEEDOR
	, A.DESCRIPCION
	, A.COLOR
	, A.TALLA
	, A.CODBARRAS
	, A.CODBARRAS2
	, A.CODBARRAS3
	, A.USASTOCKS
	, A.MARCA
	, A.ESKIT
	, A.USARNUMSERIE
	, A.UNID2V
	, A.STOCK
	, A.SECCION
FROM
	CTE_ARTICULOS_STOCK A
WHERE
		(A.USARNUMSERIE='T' AND A.TALLA<>'.')
		OR (A.USARNUMSERIE='F')
		
ORDER BY A.REFPROVEEDOR, CODBARRAS2 DESC
END
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_BUSCAR_ARTICULOS]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [rip].[APP_CONTEO_BUSCAR_ARTICULOS](@FILTRO AS NVARCHAR(50)) WITH ENCRYPTION
AS SET NOCOUNT ON
BEGIN
SET @FILTRO='%'+@FILTRO+'%'
;WITH CTE_ARTICULOS  AS (
		SELECT 
				
				distinct
				TOP 50
				A.CODARTICULO
				, A.REFPROVEEDOR
				, A.DESCRIPCION
				, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END  COLOR
				, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END TALLA 
		FROM 
				ARTICULOS A WITH(NOLOCK)
				INNER JOIN ARTICULOSLIN AL WITH(NOLOCK) ON A.CODARTICULO=AL.CODARTICULO
				INNER JOIN REFERENCIASPROV RP WITH(NOLOCK) ON A.CODARTICULO=RP.CODARTICULO
		WHERE 
				A.TIPOARTICULO='A' 
				AND A.DESCATALOGADO='F' 
				AND ( A.REFPROVEEDOR LIKE @FILTRO OR UPPER(A.DESCRIPCION) LIKE @FILTRO OR UPPER(AL.CODBARRAS) LIKE @FILTRO
				OR UPPER(AL.CODBARRAS2) LIKE @FILTRO
				OR UPPER(AL.CODBARRAS3) LIKE @FILTRO)

)
--SELECT * FROM CTE_STOCK

SELECT
	A.CODARTICULO
	, A.REFPROVEEDOR
	, A.DESCRIPCION DESCRIPCION

FROM
	CTE_ARTICULOS A

ORDER BY A.DESCRIPCION
END
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_DETALLE]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [rip].[APP_CONTEO_DETALLE] (@FECHA AS DATE
		, @ALMACEN AS NVARCHAR(3)
		, @ZONA AS NVARCHAR(50)='TODO'
		, @SECTOR AS INT=-1
		, @CODUSUARIO AS INT=-1
		, @ESTOTAL AS BIT=0
		, @SOLODIFERENCIAS AS BIT = 0
		, @CODCONCEPTO AS INT=-1 ) WITH ENCRYPTION AS 
SET NOCOUNT ON
--SET @FECHA_DEFAULT AS DATETIME = SELECT FECHAFIN FROM rip.CONTEOCAB WHERE FEHC

DECLARE @TARIFA AS INT=ISNULL((SELECT ALM.PVPETIQUETAS FROM ALMACEN ALM WITH(NOLOCK) WHERE ALM.CODALMACEN=@ALMACEN),0)

DECLARE @IDCONTEO AS INT =(SELECT IDCONTEO FROM rip.CONTEOCAB WITH(NOLOCK) WHERE FECHA=@FECHA AND CODALMACEN=@ALMACEN )

;WITH CTE_CONTEO AS(
		SELECT 
				CL.CODARTICULO
				, CL.COLOR
				, CL.TALLA
				, SUM(CL.UNIDADES) UNIDADES
				, MIN (CL.HORACONTEO) HORA
		FROM
				rip.CONTEOLIN CL WITH(NOLOCK)
		WHERE
				CL.FECHA=@FECHA
				AND CL.CODALMACEN=@ALMACEN
				AND (CL.CODUSUARIO=@CODUSUARIO OR @CODUSUARIO=-1)
				AND (CL.ZONA=@ZONA OR @ZONA='TODO')
				AND (CL.SECTOR=@SECTOR OR @SECTOR=-1)
				AND (CL.CODCONCEPTO=@CODCONCEPTO OR @CODCONCEPTO=-1)
		GROUP BY
				CL.CODARTICULO
				, CL.COLOR
				, CL.TALLA
), CTE_VENTAS AS (
		SELECT
				AVL.CODARTICULO
				, AVL.TALLA
				, AVL.COLOR
				, AVC.FECHA
				, CASE WHEN AVL.HORA<'20000101' THEN  MAX(AVC.FECHACREACION) ELSE AVL.HORA END HORA
				, SUM(AVL.UNIDADESTOTAL) UNIDADES
		FROM 
				dbo.ALBVENTACAB AVC  WITH(NOLOCK)
				INNER JOIN dbo.ALBVENTALIN AVL  WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
				
		WHERE
				AVC.FECHA>=@FECHA
				AND AVL.CODALMACEN=@ALMACEN
				AND AVL.UNIDADESTOTAL<>0
		GROUP BY
				AVL.CODARTICULO
				, AVL.TALLA
				, AVL.COLOR
				, AVC.FECHA
				, AVL.HORA 
), CTE_CONTEO_REAL AS (
		SELECT
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) CODARTICULO 
				, ISNULL(CC.COLOR, CV.COLOR) COLOR
				, ISNULL(CC.TALLA, CV.TALLA) TALLA
				, ISNULL(CC.UNIDADES,0) UNIDADES
				, ISNULL(CC.HORA, GETDATE()) HORA
				, ISNULL(SUM(CV.UNIDADES),0) VENDIDAS
		FROM 
				CTE_CONTEO CC
				LEFT JOIN CTE_VENTAS CV ON CC.CODARTICULO=CV.CODARTICULO AND CC.TALLA=CV.TALLA COLLATE Latin1_General_CS_AI AND CC.COLOR=CV.COLOR COLLATE Latin1_General_CS_AI AND CV.HORA<ISNULL(CC.HORA,GETDATE())
		GROUP BY
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) 
				, ISNULL(CC.COLOR, CV.COLOR)
				, ISNULL(CC.TALLA, CV.TALLA)
				, ISNULL(CC.UNIDADES,0)
				, ISNULL(CC.HORA, GETDATE())

), CTE_VENDIDO AS (
		SELECT
				CODARTICULO
				, COLOR
				, TALLA
				, SUM(UNIDADES) VENDIDO
		FROM
				CTE_VENTAS
		GROUP BY 
				CODARTICULO
				, COLOR
				, TALLA
)


SELECT
		ISNULL(DPTO.DESCRIPCION,'SIN DPTO') DEPARTAMENTO
		, ISNULL(S.DESCRIPCION,'SIN SECCION') SECCION
		, ISNULL(F.DESCRIPCION,'') FAMILIA
		, ISNULL(SF.DESCRIPCION,'') SUBFAMILIA
		, ISNULL(M.DESCRIPCION,'') MARCA
		, ART.CODARTICULO
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END  COLOR
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END TALLA
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END CODBARRAS
		, MAX(AL.CODBARRAS2) CODBARRAS2
		, ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)  CONTADO
		, ROUND(SUM(ISNULL(ST.STOCK,0)),3) STOCK
		, CASE WHEN ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 AND ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 
			THEN SUM(ISNULL(VEN.VENDIDO,0)) ELSE  ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) END VENDIDASVENDIDAS
		, CASE WHEN ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 AND ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 
			THEN SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(ISNULL(VEN.VENDIDO,0),0)),3)  ELSE 
			SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) END  DIFERENCIA
		, ISNULL(PV.PNETO,0) COSTO
		, ISNULL(PV.PNETO,0)*ROUND(SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3),3) COSTO_DIFERENCIA
		, '1|'+CAST(ART.CODARTICULO AS NVARCHAR(10))+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END+'|'
					+CAST(ROUND(SUM(ISNULL(CL.UNIDADES,0))+SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) AS nvarchar(10))+'|'+'0'+'|'+'0'+'|'+'0'+'|'+'|' TELESTOCK_INVENTARIO
		, '1|'+CAST(ART.CODARTICULO AS NVARCHAR(10))+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END
					+'|'+CAST(ROUND(SUM(ISNULL(CL.UNIDADES,0)),3) AS nvarchar(10))+'|'+'0'+'|'+'0'+'|'+'0'+'|'+'|' TELESTOCK_CONTADO
		, '1|'+CAST(ART.CODARTICULO AS NVARCHAR(10))+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END+'|'
					+CAST(ROUND(SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3),3) AS nvarchar(10))+'|'+'0'+'|'+'0'+'|'+'0'+'|'+'|' TELESTOCK_AJUSTE
		
FROM 
		ARTICULOS ART  WITH(NOLOCK) --ON CL.CODARTICULO=ART.CODARTICULO
		INNER JOIN rip.CONTEO_TARGET CT WITH(NOLOCK) ON ART.CODARTICULO=CT.CODARTICULO AND CT.IDCONTEO=@IDCONTEO
		INNER JOIN ARTICULOSLIN AL  WITH(NOLOCK) ON ART.CODARTICULO=AL.CODARTICULO
		LEFT JOIN DEPARTAMENTO DPTO ON ART.DPTO=DPTO.NUMDPTO
		LEFT JOIN SECCIONES S WITH(NOLOCK) ON ART.DPTO=S.NUMDPTO AND ART.SECCION=S.NUMSECCION
		LEFT JOIN FAMILIAS F WITH(NOLOCK) ON ART.DPTO=F.NUMDPTO AND ART.SECCION=F.NUMSECCION AND ART.FAMILIA=F.NUMFAMILIA
		LEFT JOIN SUBFAMILIAS SF WITH(NOLOCK) ON ART.DPTO=SF.NUMDPTO AND ART.SECCION=SF.NUMSECCION AND ART.FAMILIA=SF.NUMFAMILIA AND ART.SUBFAMILIA=SF.NUMSUBFAMILIA
		LEFT JOIN MARCA M WITH(NOLOCK) ON ART.MARCA=M.CODMARCA
		LEFT JOIN CTE_CONTEO_REAL CL ON CL.CODARTICULO=AL.CODARTICULO AND CL.COLOR=AL.COLOR COLLATE Latin1_General_CS_AI AND CL.TALLA=AL.TALLA COLLATE Latin1_General_CS_AI
		LEFT JOIN rip.CONTEOSTOCK ST WITH(NOLOCK) ON ST.CODALMACEN=@ALMACEN AND ST.FECHA=@FECHA AND AL.CODARTICULO=ST.CODARTICULO AND AL.COLOR=ST.COLOR AND AL.TALLA=ST.TALLA
		LEFT JOIN PRECIOSVENTA PV WITH(NOLOCK) ON AL.CODARTICULO=PV.CODARTICULO AND AL.COLOR=PV.COLOR AND AL.TALLA=PV.TALLA AND PV.IDTARIFAV=@TARIFA
		LEFT JOIN CTE_VENDIDO VEN ON  AL.CODARTICULO=VEN.CODARTICULO AND AL.COLOR=VEN.COLOR AND AL.TALLA=VEN.TALLA
WHERE
		(@ESTOTAL=1 AND (ST.STOCK<>0 OR CL.UNIDADES<>0 OR CL.VENDIDAS<>0))
		OR ( @ESTOTAL=0 AND (CL.UNIDADES<>0 OR CL.VENDIDAS<>0 OR VEN.VENDIDO<>0) )
	
GROUP BY
		ART.CODARTICULO
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END 
		, AL.TALLA
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END 
		, ISNULL(S.DESCRIPCION,'SIN SECCION')
		, ISNULL(DPTO.DESCRIPCION,'SIN DPTO')
		, ISNULL(F.DESCRIPCION,'')
		, ISNULL(SF.DESCRIPCION,'')
		, ISNULL(M.DESCRIPCION,'')
		, PV.PNETO
HAVING (@SOLODIFERENCIAS=0 OR SUM(ISNULL(ST.STOCK,0))-SUM(ISNULL(CL.UNIDADES,0))-SUM(ISNULL(CL.VENDIDAS,0))<>0 )


GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_DETALLE_ARTICULO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [rip].[APP_CONTEO_DETALLE_ARTICULO](@FECHA AS DATE, @ALMACEN AS NVARCHAR(3) , @CODARTICULO AS INT, @COLOR AS NVARCHAR(10), @TALLA AS NVARCHAR(10)) WITH ENCRYPTION AS
SET NOCOUNT ON
DECLARE @IDCONTEO AS INT =(SELECT IDCONTEO FROM rip.CONTEOCAB WITH(NOLOCK) WHERE FECHA=@FECHA AND CODALMACEN=@ALMACEN )
;WITH CTE_CONTEO AS(
		SELECT 
				CL.CODARTICULO
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END  COLOR
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END TALLA
				, SUM(CL.UNIDADES) UNIDADES
				, MIN (CL.HORACONTEO) HORA
				, MAX (CL.HORACONTEO) ULTCONTEO
		FROM
				rip.CONTEOLIN CL WITH(NOLOCK)
		WHERE
				CL.FECHA=@FECHA
				AND CL.CODALMACEN=@ALMACEN
				AND CL.CODARTICULO=@CODARTICULO
				AND CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END=@COLOR
				AND CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END=@TALLA
		GROUP BY
				CL.CODARTICULO
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END
), CTE_VENTAS AS (
		SELECT
				AVL.CODARTICULO
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.COLOR END  COLOR
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.TALLA END TALLA
				, AVC.FECHA
				, CASE WHEN AVL.HORA<'20000101' THEN  MAX(AVC.FECHACREACION) ELSE AVL.HORA END HORA
				, SUM(AVL.UNIDADESTOTAL) UNIDADES
		FROM 
				dbo.ALBVENTACAB AVC WITH(NOLOCK)
				INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
				
		WHERE
				AVC.FECHA>=@FECHA
				AND AVL.CODALMACEN=@ALMACEN
				AND AVL.UNIDADESTOTAL<>0
				AND AVL.CODARTICULO=@CODARTICULO
				AND CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.COLOR END=@COLOR
				AND CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.TALLA END=@TALLA
		GROUP BY
				AVL.CODARTICULO
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.COLOR END  
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.TALLA END 
				, AVC.FECHA
				, AVL.HORA 
), CTE_CONTEO_REAL AS (
		SELECT
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) CODARTICULO 
				, ISNULL(CC.COLOR, CV.COLOR) COLOR
				, ISNULL(CC.TALLA, CV.TALLA) TALLA
				, ISNULL(CC.UNIDADES,0) UNIDADES
				, ISNULL(CC.HORA, GETDATE()) HORA
				, ISNULL(SUM(CV.UNIDADES),0) VENDIDAS
				, MAX (CC.ULTCONTEO) ULTCONTEO
		FROM 
				CTE_CONTEO CC
				LEFT JOIN CTE_VENTAS CV ON CC.CODARTICULO=CV.CODARTICULO AND CC.TALLA=CV.TALLA COLLATE Latin1_General_CS_AI AND CC.COLOR=CV.COLOR COLLATE Latin1_General_CS_AI AND CV.HORA<ISNULL(CC.HORA,GETDATE())
		GROUP BY
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) 
				, ISNULL(CC.COLOR, CV.COLOR)
				, ISNULL(CC.TALLA, CV.TALLA)
				, ISNULL(CC.UNIDADES,0)
				, ISNULL(CC.HORA, GETDATE())

), CTE_VENDIDO AS (
		SELECT
				CODARTICULO
				, COLOR
				, TALLA
				, SUM(UNIDADES) VENDIDO
		FROM
				CTE_VENTAS
		GROUP BY 
				CODARTICULO
				, COLOR
				, TALLA
)


SELECT 
		ISNULL(S.DESCRIPCION,'SIN SECCION') SECCION
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END COLOR
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END TALLA
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END CODBARRAS
		--, AL.CODBARRAS2
		, ROUND(SUM(ISNULL(C.UNIDADES,0)),3) CONTADO
		, ROUND(SUM(ISNULL(ST.STOCK,0)),3) STOCK
		, ROUND(SUM(COALESCE(C.VENDIDAS,V.VENDIDO,0)),3) VENDIDAS
		, ROUND(SUM(ISNULL(ST.STOCK,0)-ISNULL(C.UNIDADES,0)-COALESCE(C.VENDIDAS,V.VENDIDO,0)),3) DIFERENCIA
		, MAX (C.ULTCONTEO) ULTCONTEO
		/*, FORMAT(ROUND(ISNULL(C.UNIDADES,0),2),'n','es-VE') CONTADO
		, FORMAT(ROUND(ISNULL(ST.STOCK,0),2),'n','es-VE') STOCK
		, FORMAT(ROUND(ISNULL(C.VENDIDAS,0),2),'n','es-VE') VENDIDAS
		, FORMAT(ROUND(ISNULL(ST.STOCK,0)-ISNULL(C.UNIDADES,0)+ISNULL(C.VENDIDAS,0),2),'n','es-VE') DIFERENCIA*/

FROM 
		dbo.ARTICULOS ART WITH(NOLOCK)
		INNER JOIN rip.CONTEO_TARGET CT WITH(NOLOCK) ON ART.CODARTICULO=CT.CODARTICULO AND CT.IDCONTEO=@IDCONTEO
		INNER JOIN ARTICULOSLIN AL WITH(NOLOCK) ON ART.CODARTICULO=AL.CODARTICULO
		LEFT JOIN SECCIONES S WITH(NOLOCK) ON ART.DPTO=S.NUMDPTO AND ART.SECCION=S.NUMSECCION
		LEFT JOIN rip.CONTEOSTOCK ST WITH(NOLOCK) ON ST.CODALMACEN=@ALMACEN AND ST.FECHA=@FECHA AND AL.CODARTICULO=ST.CODARTICULO AND AL.COLOR=ST.COLOR AND AL.TALLA=ST.TALLA
		--LEFT JOIN rip.RIP_FSTOCK_ARTICULO_FECHA(DATEADD(DAY,-1,@FECHA), @ALMACEN) ST ON AL.CODARTICULO=ST.CODARTICULO AND AL.COLOR=ST.COLOR AND AL.TALLA=ST.TALLA
		LEFT JOIN CTE_CONTEO_REAL C ON AL.CODARTICULO=C.CODARTICULO AND AL.COLOR=C.COLOR COLLATE Latin1_General_CS_AI AND AL.TALLA=C.TALLA COLLATE Latin1_General_CS_AI
		LEFT JOIN CTE_VENDIDO V ON AL.CODARTICULO=V.CODARTICULO AND AL.TALLA=V.TALLA AND AL.COLOR=V.COLOR
WHERE
		ART.USASTOCKS='T'
		AND (C.UNIDADES<>0 OR ST.STOCK<>0 OR C.VENDIDAS<>0)
		AND ART.CODARTICULO=@CODARTICULO
		AND (AL.COLOR=@COLOR
			AND AL.TALLA=@TALLA
			OR @TALLA='@')
		--AND ((NOT C.CODARTICULO IS NULL AND @SOLO_CONTADO=1)OR @SOLO_CONTADO=0 )
GROUP BY
		ISNULL(S.DESCRIPCION,'SIN SECCION')
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END 
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END 
ORDER BY ULTCONTEO DESC
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_GETCONTEO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [rip].[APP_CONTEO_GETCONTEO] (@FECHA AS DATE
		, @ALMACEN AS NVARCHAR(3)
		, @ZONA AS NVARCHAR(50)='TODO'
                , @SECTOR AS INT=-1
		, @CODUSUARIO AS INT=-1
		, @ESTOTAL AS BIT=0
		, @SOLODIFERENCIAS AS BIT = 0
		, @CODCONCEPTO AS INT=-1
		) WITH ENCRYPTION AS
SET NOCOUNT ON

DECLARE @IDCONTEO AS INT =(SELECT IDCONTEO FROM rip.CONTEOCAB WITH(NOLOCK) WHERE FECHA=@FECHA AND CODALMACEN=@ALMACEN )

-- NUEVO (2026-07-16, ver memoria stock-mermas-conteo): ubicar el almacen de mermas
-- de esta tienda (mismo prefijo de codigo, ESMERMAS=1), para exponer STOCKMERMAS.
DECLARE @ALMACENMERMA AS NVARCHAR(3) = (
	SELECT TOP 1 CODALMACEN
	FROM ALMACEN WITH(NOLOCK)
	WHERE ESMERMAS = 1
	  AND LEFT(CODALMACEN, LEN(CODALMACEN)-1) = LEFT(@ALMACEN, LEN(@ALMACEN)-1)
)

;WITH CTE_CONTEO AS(
		SELECT 
				CL.CODARTICULO
				, CL.COLOR
				, CL.TALLA
				, SUM(CL.UNIDADES) UNIDADES
				, MIN (CL.HORACONTEO) HORA
				, MAX (CL.HORACONTEO) ULTCONTEO
		FROM
				rip.CONTEOLIN CL WITH(NOLOCK)
		WHERE
				CL.FECHA=@FECHA
				AND CL.CODALMACEN=@ALMACEN
				AND (CL.CODUSUARIO=@CODUSUARIO OR @CODUSUARIO=-1)
				AND (CL.ZONA=@ZONA OR @ZONA='TODO')
                                AND (CL.SECTOR=@SECTOR OR @SECTOR=-1)
				AND (CL.CODCONCEPTO=@CODCONCEPTO OR @CODCONCEPTO=-1)
		GROUP BY
				CL.CODARTICULO
				, CL.COLOR
				, CL.TALLA
), CTE_VENTAS AS (
		SELECT
				AVL.CODARTICULO
				, AVL.TALLA
				, AVL.COLOR
				, AVC.FECHA
				, CASE WHEN AVL.HORA<'20000101' THEN  MAX(AVC.FECHACREACION) ELSE AVL.HORA END HORA
				, SUM(AVL.UNIDADESTOTAL) UNIDADES
		FROM 
				dbo.ALBVENTACAB AVC  WITH(NOLOCK)
				INNER JOIN dbo.ALBVENTALIN AVL  WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
				
		WHERE
				AVC.FECHA>=@FECHA
				AND AVL.CODALMACEN=@ALMACEN
				AND AVL.UNIDADESTOTAL<>0
		GROUP BY
				AVL.CODARTICULO
				, AVL.TALLA
				, AVL.COLOR
				, AVC.FECHA
				, AVL.HORA 
), CTE_CONTEO_REAL AS (
		SELECT
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) CODARTICULO 
				, ISNULL(CC.COLOR, CV.COLOR) COLOR
				, ISNULL(CC.TALLA, CV.TALLA) TALLA
				, ISNULL(CC.UNIDADES,0) UNIDADES
				, ISNULL(CC.HORA, GETDATE()) HORA
				, ISNULL(SUM(CV.UNIDADES),0) VENDIDAS
				, MAX(CC.ULTCONTEO) ULTCONTEO
		FROM 
				CTE_CONTEO CC
				LEFT JOIN CTE_VENTAS CV ON CC.CODARTICULO=CV.CODARTICULO AND CC.TALLA=CV.TALLA COLLATE Latin1_General_CS_AI AND CC.COLOR=CV.COLOR COLLATE Latin1_General_CS_AI AND CV.HORA<ISNULL(CC.HORA,GETDATE())
		GROUP BY
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) 
				, ISNULL(CC.COLOR, CV.COLOR)
				, ISNULL(CC.TALLA, CV.TALLA)
				, ISNULL(CC.UNIDADES,0)
				, ISNULL(CC.HORA, GETDATE())

), CTE_VENDIDO AS (
		SELECT
				CODARTICULO
				, COLOR
				, TALLA
				, SUM(UNIDADES) VENDIDO
		FROM
				CTE_VENTAS
		GROUP BY 
				CODARTICULO
				, COLOR
				, TALLA
)



SELECT 
		ART.CODARTICULO
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END  COLOR
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END TALLA
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END CODBARRAS
		--,'' COLOR
		--, '' TALLA
		, ISNULL(DPTO.DESCRIPCION,'') DEPARTAMENTO
		, ISNULL(SEC.DESCRIPCION,'') SECCION
		, ART.REFPROVEEDOR
                , ART.NORMA
		, ART.DESCRIPCION
		, ROUND(SUM(ISNULL(CL.UNIDADES,0)),3) UNIDADES
		, CASE WHEN ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 AND ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 
			THEN SUM(ISNULL(VEN.VENDIDO,0)) ELSE  ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) END VENDIDAS --ESTO PARA LOS PRODUCTOS QUE SE VENDIERON EN SU TOTALIDAD SIN CONTARLOS
		, SUM(ISNULL(VEN.VENDIDO,0)) VENTA_REAL
		, SUM(ISNULL(S.STOCK,0)) STOCK
		, SUM(ISNULL(SM.STOCK,0)) STOCKMERMAS -- NUEVO: stock del almacen de mermas
		, CASE WHEN ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 AND ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0
			THEN SUM(ISNULL(S.STOCK,0))-ROUND(SUM(ISNULL(ISNULL(VEN.VENDIDO,0),0)),3)  ELSE
			SUM(ISNULL(S.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) END PORCONTAR
		, MAX(CL.ULTCONTEO) ULTCONTEO

FROM
		ARTICULOS ART  WITH(NOLOCK) --ON CL.CODARTICULO=ART.CODARTICULO
		INNER JOIN rip.CONTEO_TARGET CT WITH(NOLOCK) ON ART.CODARTICULO=CT.CODARTICULO AND CT.IDCONTEO=@IDCONTEO
		INNER JOIN ARTICULOSLIN AL  WITH(NOLOCK) ON ART.CODARTICULO=AL.CODARTICULO
		LEFT JOIN CTE_CONTEO_REAL CL ON CL.CODARTICULO=AL.CODARTICULO AND CL.COLOR=AL.COLOR COLLATE Latin1_General_CS_AI AND CL.TALLA=AL.TALLA COLLATE Latin1_General_CS_AI
		LEFT JOIN DEPARTAMENTO DPTO WITH(NOLOCK) ON ART.DPTO=DPTO.NUMDPTO
		LEFT JOIN SECCIONES SEC  WITH(NOLOCK) ON ART.DPTO=SEC.NUMDPTO AND ART.SECCION=SEC.NUMSECCION
		LEFT JOIN rip.CONTEOSTOCK S WITH(NOLOCK) ON S.CODALMACEN=@ALMACEN AND S.FECHA=@FECHA AND AL.CODARTICULO=S.CODARTICULO AND AL.COLOR=S.COLOR AND AL.TALLA=S.TALLA
		LEFT JOIN STOCKS SM WITH(NOLOCK) ON SM.CODALMACEN=@ALMACENMERMA AND AL.CODARTICULO=SM.CODARTICULO AND AL.COLOR=SM.COLOR AND AL.TALLA=SM.TALLA -- NUEVO
		LEFT JOIN CTE_VENDIDO VEN ON  AL.CODARTICULO=VEN.CODARTICULO AND AL.COLOR=VEN.COLOR AND AL.TALLA=VEN.TALLA

WHERE
		(@ESTOTAL=1 AND (S.STOCK<>0 OR CL.UNIDADES<>0 OR CL.VENDIDAS<>0))
		OR ( @ESTOTAL=0 AND (CL.UNIDADES<>0 OR CL.VENDIDAS<>0 OR VEN.VENDIDO<>0) )

GROUP BY
		ART.CODARTICULO
                , ART.NORMA
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END
		, AL.TALLA
		, ISNULL(DPTO.DESCRIPCION,'')
		, ISNULL(SEC.DESCRIPCION,'')
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END

HAVING (@SOLODIFERENCIAS=0 OR SUM(ISNULL(S.STOCK,0))-SUM(ISNULL(CL.UNIDADES,0))-SUM(ISNULL(CL.VENDIDAS,0))<>0 )
ORDER BY ULTCONTEO DESC

GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_GETCONTEO_ARTICULO]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [rip].[APP_CONTEO_GETCONTEO_ARTICULO](@FECHA AS DATE , @ALMACEN AS NVARCHAR(3) , @CODARTICULO AS INT,  @COLOR AS NVARCHAR(10), @TALLA AS NVARCHAR(10)) WITH ENCRYPTION AS
SET NOCOUNT ON

SELECT 
		CL.ID
		, AL.CODARTICULO
		, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END  COLOR
		, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END TALLA 
		, ISNULL(AL.CODBARRAS,'-') CODBARRAS
		, ISNULL(AL.CODBARRAS2,'-') CODBARRAS2
		, CL.UNIDADES
		, CL.HORACONTEO
		, CL.ZONA
		, ISNULL(V.NOMVENDEDOR,'-') USUARIO
		, ISNULL(CC.CONCEPTO,'-') CONCEPTO
FROM 
		rip.CONTEOLIN CL WITH(NOLOCK)
		INNER JOIN ARTICULOSLIN AL WITH(NOLOCK) ON CL.CODARTICULO=AL.CODARTICULO AND CL.TALLA=AL.TALLA COLLATE Latin1_General_CS_AI AND CL.COLOR=AL.COLOR COLLATE Latin1_General_CS_AI
		LEFT JOIN VENDEDORES V WITH(NOLOCK) ON CL.CODUSUARIO=V.CODVENDEDOR
		LEFT JOIN rip.CONCEPTOS_CONTEO CC ON CL.CODCONCEPTO=CC.CODCONCEPTO

WHERE
		CL.FECHA=@FECHA
		AND CL.CODALMACEN=@ALMACEN
		AND CL.CODARTICULO=@CODARTICULO
		AND CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END=@COLOR
		AND CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END=@TALLA

GO
/****** Object:  StoredProcedure [ripWsRep].[GET_ALMACENES]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [ripWsRep].[GET_ALMACENES] WITH ENCRYPTION AS
SET NOCOUNT ON

	SELECT CODALMACEN, NOMBREALMACEN FROM ALMACEN ALM WHERE ALM.ESMERMAS=0
GO
/****** Object:  StoredProcedure [ripWsRep].[GET_VENDEDORES]    Script Date: 11/9/2023 9:25:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [ripWsRep].[GET_VENDEDORES] WITH ENCRYPTION AS
SET NOCOUNT ON
	SELECT 
		V.CODVENDEDOR
		, V.NOMVENDEDOR
		, V.FOTO 
                , '0010000000' PERMISOS
		--, RTRIM(LTRIM(ISNULL(POBLACIONBANCO,''))) + REPLICATE( '0', 10-LEN(RTRIM(LTRIM(ISNULL(POBLACIONBANCO,''))) ))   PERMISOS
	FROM 
		VENDEDORES V WITH(NOLOCK)
	WHERE 
		V.DESCATALOGADO='F' AND LTRIM(RTRIM(ISNULL(V.NEWPASSENTRADA,'')))<>''  
                --AND  V.TIPOUSUARIO IN (0,1,5,113,86)
                AND V.VISIBILIDAD IN (98,99)
		--AND RTRIM(LTRIM(ISNULL(POBLACIONBANCO,''))) + REPLICATE( '0', 10-LEN(RTRIM(LTRIM(ISNULL(POBLACIONBANCO,''))) ))<>'0000000000'
		--AND V.TIPOUSUARIO=0
GO
/****** Object:  StoredProcedure [rip].[APP_CONTEO_DETALLE_PTY]    Script Date: 2/4/2024 11:16:09 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [rip].[APP_CONTEO_DETALLE_PTY] (
		@FECHA AS DATE
		, @ALMACEN AS NVARCHAR(3)
		, @ZONA AS NVARCHAR(50)='TODO'
		, @SECTOR AS INT=-1
		, @CODUSUARIO AS INT=-1
		, @ESTOTAL AS BIT=0
		, @SOLODIFERENCIAS AS BIT = 0
		, @CODCONCEPTO AS INT=-1 ) WITH ENCRYPTION AS
		
SET NOCOUNT ON
--SET @FECHA_DEFAULT AS DATETIME = SELECT FECHAFIN FROM rip.CONTEOCAB WHERE FEHC

DECLARE @TARIFA AS INT=ISNULL((SELECT ALM.PVPETIQUETAS FROM ALMACEN ALM WITH(NOLOCK) WHERE ALM.CODALMACEN=@ALMACEN),0)

DECLARE @IDCONTEO AS INT =(SELECT IDCONTEO FROM rip.CONTEOCAB WITH(NOLOCK) WHERE FECHA=@FECHA AND CODALMACEN=@ALMACEN )

;WITH CTE_CONTEO AS(
		SELECT 
				CL.CODARTICULO
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END COLOR
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END TALLA
				, SUM(CL.UNIDADES) UNIDADES
				, MIN (CL.HORACONTEO) HORA
		FROM
				rip.CONTEOLIN CL WITH(NOLOCK)
		WHERE
				CL.FECHA=@FECHA
				AND CL.CODALMACEN=@ALMACEN
				AND (CL.CODUSUARIO=@CODUSUARIO OR @CODUSUARIO=-1)
				AND (CL.ZONA=@ZONA OR @ZONA='TODO')
				AND (CL.SECTOR=@SECTOR OR @SECTOR=-1)
				AND (CL.CODCONCEPTO=@CODCONCEPTO OR @CODCONCEPTO=-1)
		GROUP BY
				CL.CODARTICULO
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.COLOR END 
				, CASE WHEN CL.TALLA IN ('@') THEN '.' ELSE  CL.TALLA END 
), CTE_VENTAS AS (
		SELECT
				AVL.CODARTICULO
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.COLOR END COLOR
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.TALLA END TALLA
				, AVC.FECHA
				, CASE WHEN AVL.HORA<'20000101' THEN  MAX(AVC.FECHACREACION) ELSE AVL.HORA END HORA
				, SUM(AVL.UNIDADESTOTAL) UNIDADES
		FROM 
				dbo.ALBVENTACAB AVC  WITH(NOLOCK)
				INNER JOIN dbo.ALBVENTALIN AVL  WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
				
		WHERE
				AVC.FECHA>=@FECHA
				AND AVL.CODALMACEN=@ALMACEN
				AND AVL.UNIDADESTOTAL<>0
		GROUP BY
				AVL.CODARTICULO
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.COLOR END 
				, CASE WHEN AVL.TALLA IN ('@') THEN '.' ELSE  AVL.TALLA END
				, AVC.FECHA
				, AVL.HORA 
), CTE_CONTEO_REAL AS (
		SELECT
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) CODARTICULO 
				, ISNULL(CC.COLOR, CV.COLOR) COLOR
				, ISNULL(CC.TALLA, CV.TALLA) TALLA
				, ISNULL(CC.UNIDADES,0) UNIDADES
				, ISNULL(CC.HORA, GETDATE()) HORA
				, ISNULL(SUM(CV.UNIDADES),0) VENDIDAS
		FROM 
				CTE_CONTEO CC
				LEFT JOIN CTE_VENTAS CV ON CC.CODARTICULO=CV.CODARTICULO AND CC.TALLA=CV.TALLA COLLATE Latin1_General_CS_AI AND CC.COLOR=CV.COLOR COLLATE Latin1_General_CS_AI AND CV.HORA<ISNULL(CC.HORA,GETDATE())
		GROUP BY
				ISNULL(CC.CODARTICULO, CV.CODARTICULO) 
				, ISNULL(CC.COLOR, CV.COLOR)
				, ISNULL(CC.TALLA, CV.TALLA)
				, ISNULL(CC.UNIDADES,0)
				, ISNULL(CC.HORA, GETDATE())

), CTE_VENDIDO AS (
		SELECT
				CODARTICULO
				, COLOR
				, TALLA
				, SUM(UNIDADES) VENDIDO
		FROM
				CTE_VENTAS
		GROUP BY 
				CODARTICULO
				, COLOR
				, TALLA
), CTE_CONTEO_ZONA AS (
SELECT
	CL.CODARTICULO
	, CASE WHEN CL.TALLA='@' THEN '.' ELSE  CL.TALLA END TALLA
	, CASE WHEN CL.TALLA='@' THEN '.' ELSE  CL.COLOR END  COLOR
	, SUM(CASE WHEN CL.CODCONCEPTO=1  THEN CL.UNIDADES ELSE 0 END) ZONA_1
	, SUM(CASE WHEN CL.CODCONCEPTO=2  THEN CL.UNIDADES ELSE 0 END) ZONA_2
	, SUM(CASE WHEN CL.CODCONCEPTO=3  THEN CL.UNIDADES ELSE 0 END) ZONA_3
	, SUM(CASE WHEN CL.CODCONCEPTO=4  THEN CL.UNIDADES ELSE 0 END) ZONA_4
	, SUM(CASE WHEN CL.CODCONCEPTO=5  THEN CL.UNIDADES ELSE 0 END) ZONA_5
	, SUM(CASE WHEN CL.CODCONCEPTO=6  THEN CL.UNIDADES ELSE 0 END) ZONA_6
	, SUM(CASE WHEN CL.CODCONCEPTO=7  THEN CL.UNIDADES ELSE 0 END) ZONA_7
	, SUM(CL.UNIDADES) CONTADO
FROM
	rip.CONTEOLIN CL WITH(NOLOCK)
WHERE 
	CL.FECHA=@FECHA AND CL.CODALMACEN=@ALMACEN 
GROUP BY
	CL.CODARTICULO
	, CASE WHEN CL.TALLA='@' THEN '.' ELSE  CL.TALLA END 
	, CASE WHEN CL.TALLA='@' THEN '.' ELSE  CL.COLOR END 
)


SELECT
		CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END CODBARRAS
		, MAX(AL.CODBARRAS2) CODBARRAS2
		, ART.CODARTICULO
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, ISNULL(ART.DESCRIPADIC,'') ADICIONAL
		, ISNULL(DPTO.DESCRIPCION,'SIN DPTO') DEPARTAMENTO
		, ISNULL(S.DESCRIPCION,'SIN SECCION') SECCION
		, ISNULL(F.DESCRIPCION,'') FAMILIA
		, ISNULL(SF.DESCRIPCION,'') SUBFAMILIA
		, ISNULL(M.DESCRIPCION,'') MARCA
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END TALLA
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END  COLOR
		, CZ.ZONA_1
		, CZ.ZONA_2
		, CZ.ZONA_3
		, CZ.ZONA_4
		, CZ.ZONA_5
		, CZ.ZONA_6
		, CZ.ZONA_7
		, ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)  CONTADO
		, ROUND(SUM(ISNULL(ST.STOCK,0)),3) STOCK
		, CASE WHEN ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 AND ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 
			THEN SUM(ISNULL(VEN.VENDIDO,0)) ELSE  ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) END VENDIDAS
		, CASE WHEN ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 AND ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)=0 
			THEN SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(ISNULL(VEN.VENDIDO,0),0)),3)  ELSE 
			SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) END  DIFERENCIA
		, ROUND(ISNULL(MAX(CPA.COSTESTOCK),0),2) COSTO
		, ISNULL(PV.PNETO,0) COSTOVEN
		, ISNULL(PV.PNETO,0)*ROUND(SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3),3) COSTOVEN_DIFERENCIA
		/*, '1|'+CAST(ART.CODARTICULO AS NVARCHAR(10))+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END+'|'
					+CAST(ROUND(SUM(ISNULL(CL.UNIDADES,0))+SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3) AS nvarchar(10))+'|'+'0'+'|'+'0'+'|'+'0'+'|'+'|' TELESTOCK_INVENTARIO
		, '1|'+CAST(ART.CODARTICULO AS NVARCHAR(10))+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END+'|'
					+CAST(ROUND(SUM(ISNULL(CL.UNIDADES,0)),3) AS nvarchar(10))+'|'+'0'+'|'+'0'+'|'+'0'+'|'+'|' TELESTOCK_CONTADO
		, '1|'+CAST(ART.CODARTICULO AS NVARCHAR(10))+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END+'|'+CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END+'|'
					+CAST(ROUND(SUM(ISNULL(ST.STOCK,0))-ROUND(SUM(ISNULL(CL.UNIDADES,0)),3)-ROUND(SUM(ISNULL(ISNULL(CL.VENDIDAS,0),0)),3),3) AS nvarchar(10))+'|'+'0'+'|'+'0'+'|'+'0'+'|'+'|' TELESTOCK_AJUSTE*/
		
		
FROM 
		ARTICULOS ART  WITH(NOLOCK) --ON CL.CODARTICULO=ART.CODARTICULO
		INNER JOIN rip.CONTEO_TARGET CT WITH(NOLOCK) ON ART.CODARTICULO=CT.CODARTICULO AND CT.IDCONTEO=@IDCONTEO
		INNER JOIN ARTICULOSLIN AL  WITH(NOLOCK) ON ART.CODARTICULO=AL.CODARTICULO
		LEFT JOIN DEPARTAMENTO DPTO ON ART.DPTO=DPTO.NUMDPTO
		LEFT JOIN SECCIONES S WITH(NOLOCK) ON ART.DPTO=S.NUMDPTO AND ART.SECCION=S.NUMSECCION
		LEFT JOIN FAMILIAS F WITH(NOLOCK) ON ART.DPTO=F.NUMDPTO AND ART.SECCION=F.NUMSECCION AND ART.FAMILIA=F.NUMFAMILIA
		LEFT JOIN SUBFAMILIAS SF WITH(NOLOCK) ON ART.DPTO=SF.NUMDPTO AND ART.SECCION=SF.NUMSECCION AND ART.FAMILIA=SF.NUMFAMILIA AND ART.SUBFAMILIA=SF.NUMSUBFAMILIA
		LEFT JOIN CTE_CONTEO_REAL CL ON CL.CODARTICULO=AL.CODARTICULO AND CL.COLOR=AL.COLOR COLLATE Latin1_General_CS_AI AND CL.TALLA=AL.TALLA COLLATE Latin1_General_CS_AI
		LEFT JOIN CTE_CONTEO_ZONA CZ ON CZ.CODARTICULO=AL.CODARTICULO AND CZ.COLOR=AL.COLOR COLLATE Latin1_General_CS_AI AND CZ.TALLA=AL.TALLA COLLATE Latin1_General_CS_AI
		LEFT JOIN rip.CONTEOSTOCK ST WITH(NOLOCK) ON ST.CODALMACEN=@ALMACEN AND ST.FECHA=@FECHA AND AL.CODARTICULO=ST.CODARTICULO AND AL.COLOR=ST.COLOR AND AL.TALLA=ST.TALLA
		LEFT JOIN COSTESPORALMACEN CPA WITH(NOLOCK) ON AL.CODARTICULO=CPA.CODARTICULO AND AL.COLOR=CPA.COLOR AND AL.TALLA=CPA.TALLA AND CPA.CODALMACEN=@ALMACEN
		LEFT JOIN CTE_VENDIDO VEN ON  AL.CODARTICULO=VEN.CODARTICULO AND AL.COLOR=VEN.COLOR AND AL.TALLA=VEN.TALLA
		LEFT JOIN PRECIOSVENTA PV WITH(NOLOCK) ON AL.CODARTICULO=PV.CODARTICULO AND AL.COLOR=PV.COLOR AND AL.TALLA=PV.TALLA AND PV.IDTARIFAV=@TARIFA
		LEFT JOIN MARCA M WITH(NOLOCK) ON ART.MARCA=M.CODMARCA
WHERE
		(@ESTOTAL=1 AND (ST.STOCK<>0 OR CL.UNIDADES<>0 OR CL.VENDIDAS<>0))
		OR ( @ESTOTAL=0 AND (CL.UNIDADES<>0 OR CL.VENDIDAS<>0 OR VEN.VENDIDO<>0) )
	
GROUP BY
		ART.CODARTICULO
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.COLOR END 
		, CASE WHEN AL.TALLA IN ('@') THEN '.' ELSE  AL.TALLA END 
		, ART.REFPROVEEDOR
		, ART.DESCRIPCION
		, ART.DESCRIPADIC
		, CASE WHEN AL.TALLA IN ('@') THEN '' ELSE  AL.CODBARRAS END 
		, ISNULL(S.DESCRIPCION,'SIN SECCION')
		, ISNULL(DPTO.DESCRIPCION,'SIN DPTO')
		, ISNULL(F.DESCRIPCION,'')
		, ISNULL(SF.DESCRIPCION,'')
		, ISNULL(M.DESCRIPCION,'')
		, PV.PNETO
		, CZ.ZONA_1
		, CZ.ZONA_2
		, CZ.ZONA_3
		, CZ.ZONA_4
		, CZ.ZONA_5
		, CZ.ZONA_6
		, CZ.ZONA_7
		--, CPA.COSTESTOCK
HAVING (@SOLODIFERENCIAS=0 OR SUM(ISNULL(ST.STOCK,0))-SUM(ISNULL(CL.UNIDADES,0))-SUM(ISNULL(CL.VENDIDAS,0))<>0)
GO


